CREATE DATABASE IF NOT EXISTS `moviedb` DEFAULT CHARACTER SET latin1;
USE `moviedb`;

DROP TABLE IF EXISTS `sales`;
DROP TABLE IF EXISTS `customers`;
DROP TABLE IF EXISTS `creditcards`;
DROP TABLE IF EXISTS `genres_in_movies`;
DROP TABLE IF EXISTS `genres`;
DROP TABLE IF EXISTS `stars_in_movies`;
DROP TABLE IF EXISTS `stars`;
DROP TABLE IF EXISTS `movies`;

CREATE TABLE `movies` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`title` VARCHAR(100) NOT NULL DEFAULT '',
	`year` INTEGER NOT NULL,
	`director` VARCHAR(100) NOT NULL DEFAULT '',
	`banner_url` VARCHAR(200),
	`trailer_url` VARCHAR(200),
	PRIMARY KEY (`id`)
) AUTO_INCREMENT=0 ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE `stars` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`first_name` VARCHAR(50) NOT NULL DEFAULT '',
	`last_name` VARCHAR(50) NOT NULL DEFAULT '',
	`dob` DATE,
	`photo_url` VARCHAR(200),
	PRIMARY KEY (`id`)
) AUTO_INCREMENT=0 ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE `stars_in_movies` (
	`star_id` INTEGER NOT NULL,
	`movie_id` INTEGER NOT NULL,
	PRIMARY KEY (`star_id`, `movie_id`),
	FOREIGN KEY (`star_id`)
		REFERENCES `stars` (`id`)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (`movie_id`)
		REFERENCES `movies` (`id`)
		ON DELETE CASCADE ON UPDATE CASCADE
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE `genres` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`name` VARCHAR(32) NOT NULL DEFAULT '',
	PRIMARY KEY (`id`)
) AUTO_INCREMENT=0 ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE `genres_in_movies` (
	`genre_id` INTEGER NOT NULL,
	`movie_id` INTEGER NOT NULL,
	PRIMARY KEY (`genre_id`, `movie_id`),
	FOREIGN KEY (`genre_id`)
		REFERENCES `genres` (`id`)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (`movie_id`)
		REFERENCES `movies` (`id`)
		ON DELETE CASCADE ON UPDATE CASCADE
) AUTO_INCREMENT=0 ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE `creditcards` (
	`id` VARCHAR(20) NOT NULL,
	`first_name` VARCHAR(50) NOT NULL DEFAULT '',
	`last_name` VARCHAR(50) NOT NULL DEFAULT '',
	`expiration` DATE NOT NULL,
	PRIMARY KEY (`id`)
) ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE `customers` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`first_name` VARCHAR(50) NOT NULL DEFAULT '',
	`last_name` VARCHAR(50) NOT NULL DEFAULT '',
	`cc_id` VARCHAR(20) NOT NULL DEFAULT '',
	`address` VARCHAR(200) NOT NULL DEFAULT '',
	`email` VARCHAR(50) NOT NULL DEFAULT '',
	`password` VARCHAR(20) NOT NULL DEFAULT '',
	PRIMARY KEY (`id`),
	FOREIGN KEY (`cc_id`)
		REFERENCES `creditcards` (`id`)
		ON DELETE CASCADE ON UPDATE CASCADE
) AUTO_INCREMENT=0 ENGINE=INNODB DEFAULT CHARSET=LATIN1;

CREATE TABLE `sales` (
	`id` INTEGER NOT NULL AUTO_INCREMENT,
	`customer_id` INTEGER NOT NULL,
	`movie_id` INTEGER NOT NULL,
	`sale_date` DATE NOT NULL,
	PRIMARY KEY (`id`),
	FOREIGN KEY (`customer_id`)
		REFERENCES `customers` (`id`)
		ON DELETE CASCADE ON UPDATE CASCADE,
	FOREIGN KEY (`movie_id`)
		REFERENCES `movies` (`id`)
		ON DELETE CASCADE ON UPDATE CASCADE
) AUTO_INCREMENT=0 ENGINE=INNODB DEFAULT CHARSET=LATIN1;